### ISSUE TITLE
[BUG] Docker package seems to be private or nonexistant

### ISSUE THREAD

**Issue by kanielrkirby** [eklairs/tlock#1]
### Describe the bug 🐛

When running the command for pulling the image, it gives the following error:

```
Error: initializing source docker://ghcr.io/eklairs/tlock:latest: reading manifest latest in ghcr.io/eklairs/tlock: denied
```

You'll also see from the screenshot that it is missing the `Packages`.

### To Reproduce 🐣

1. Install Docker, Podman, etc.
2. Run the command from the README.md: `docker run -it --rm ghcr.io/eklairs/tlock:latest`. (or `pull`)

### Expected behavior 🤔

Should pull the package and run it.

### Screenshots 🧐

![20240512-133033](https://github.com/eklairs/tlock/assets/77940607/20fe21fc-b054-4c49-a54d-2079adde95b7)

### How did you download tlock?

None

### What is your operating system?

None

**Comment by eklairs** [comment]
Hi!

Oops, I forgot to make it public. Thanks for reporting it!
It is public now, lemme know it it works or not.
