### ISSUE TITLE
[WAYLAND] [BUG] Screenshot qrcode doesn't work

### ISSUE THREAD

**Issue by olivertzeng** [eklairs/tlock#6]
### To Reproduce 🐣

1. Press `s`
2. Press `<CR>`
3. have a qrcode in the same screen
4. doesnt work

### Expected behavior 🤔

Works

### How did you download tlock?

AUR

### What is your operating system?

Linux

**Comment by eklairs** [comment]
Hm.... weird. Are you sure that the QRCode is valid? What error message do you see in the middle?

**Comment by olivertzeng** [comment]
I forgotBut it was something like it cannot be found
 Sent from Proton Mail for iOS 
於 週日, 5月 19, 2024 時間 10:16, eklairs ***@***.***&gt; 寫道：  Hm.... weird. Are you sure that the QRCode is valid? What error message do you see in the middle?

**Comment by olivertzeng** [comment]
Can you show me how it’s scanned?
 Sent from Proton Mail for iOS 
於 週日, 5月 19, 2024 時間 10:16, eklairs ***@***.***&gt; 寫道：  Hm.... weird. Are you sure that the QRCode is valid? What error message do you see in the middle?

**Comment by eklairs** [comment]
> I forgotBut it was something like it cannot be found

Well I did face a similar bug yesterday while trying the qrcode which maybe also the cause for your's. I will fix that and let you know :)

**Comment by eklairs** [comment]
> Can you show me how it’s scanned?

Once you are in dashboard, press `s` (or the key if you have custom keybindings) to go to from screen window. And like this:

 

https://github.com/eklairs/tlock/assets/142717667/843ecf81-be48-4999-9b03-ed37fec55b1b

**Comment by olivertzeng** [comment]
Ty will try that method
 Sent from Proton Mail for iOS 
於 週日, 5月 19, 2024 時間 11:00, eklairs ***@***.***&gt; 寫道：  
Can you show me how it’s scanned?

Once you are in dashboard, press s (or the key if you have custom keybindings) to go to from screen window. And like this:
https://github.com/eklairs/tlock/assets/142717667/843ecf81-be48-4999-9b03-ed37fec55b1b

**Comment by olivertzeng** [comment]
Did not find any token

**Comment by eklairs** [comment]
Wait, are you on Wayland by any chance? or X11?

**Comment by olivertzeng** [comment]
Wayland
 Sent from Proton Mail for iOS 
於 週日, 5月 19, 2024 時間 12:01, eklairs ***@***.***&gt; 寫道：  Wait, are you on Wayland? or X11?

**Comment by eklairs** [comment]
Ah i see.... the screenshot library doesnt work for wayland, so that is the issue. Though i will try to workaround this issue :)
